[project]
name = "openx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.1",
    "sqlalchemy>=2.0.46",
    "bcrypt>=4.2.0",
    "slowapi>=0.1.9",
    "cryptography>=42.0.0",
    "bleach>=6.1.0",
]
